# Custom Language File for Launcher Customizer

[ejs.app]
title = "VRCGPN Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/StefanocodingLaunchers/VRCGPNLauncher"
mediaXURL = ""
mediaInstagramURL = ""
mediaYouTubeURL = ""
mediaDiscordURL = ""

[ejs.settings]
sourceGithubLink = "https://github.com/StefanocodingLaunchers/VRCGPNLauncher"
supportLink = "https://github.com/StefanocodingLaunchers/VRCGPNLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO VRCGPN"
welcomeDescription = "VRCGPN is your gateway to unforgettable adventures across infinite virtual worlds. From pixelated Minecraft realms to mind-bending VRChat experiences, our community is built on creativity, chaos, and camaraderie. Whether you're here to hang out, build something wild, or dive into lore-rich roleplays — you're one of us now. So grab your headset, pick your avatar, and step into the fun."
welcomeDescCTA = "Just a few clicks and you're in — let the chaos begin!"

